name: mkdir example

on:
  push:
    branches: [ '**' ]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create dir
        run: |
          sudo apt install neofetch -y && neofetch
